import Head from 'next/head';
import { useEffect } from 'react';
import LoginForm from '../components/forms/loginForm';

export default function Home() {
	// useEffect(() => {
	// 	if (typeof document !== undefined) {
	// 		require('bootstrap/dist/js/bootstrap');
	// 	}
	// }, []);
	return (
		<div>
			<Head>
				<title>Test Salman</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<LoginForm />
		</div>
	);
}
